/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BlogCtfCuhk25ctfPermutationsImport } from './routes/blog/ctf/cuhk25ctf/permutations'
import { Route as BlogCtfCuhk25ctfIammrcowormrcloudImport } from './routes/blog/ctf/cuhk25ctf/iam_mr_cow_or_mr_cloud'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BlogCtfCuhk25ctfPermutationsRoute =
  BlogCtfCuhk25ctfPermutationsImport.update({
    path: '/blog/ctf/cuhk25ctf/permutations',
    getParentRoute: () => rootRoute,
  } as any)

const BlogCtfCuhk25ctfIammrcowormrcloudRoute =
  BlogCtfCuhk25ctfIammrcowormrcloudImport.update({
    path: '/blog/ctf/cuhk25ctf/iam_mr_cow_or_mr_cloud',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/ctf/cuhk25ctf/iam_mr_cow_or_mr_cloud': {
      preLoaderRoute: typeof BlogCtfCuhk25ctfIammrcowormrcloudImport
      parentRoute: typeof rootRoute
    }
    '/blog/ctf/cuhk25ctf/permutations': {
      preLoaderRoute: typeof BlogCtfCuhk25ctfPermutationsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BlogCtfCuhk25ctfIammrcowormrcloudRoute,
  BlogCtfCuhk25ctfPermutationsRoute,
])

/* prettier-ignore-end */
